### ISSUE TITLE
Server browser uses wrong port and thus my server is listed as unreachable

### ISSUE THREAD

**Issue by Eric-Prokop** [TES3MP/openmw-tes3mp#687]
The port in the server browser is not the port I configured my server with. Thus, the master server says my server is unreachable and I can not connect to it using the server browser. 

If I use the client directly with the `--connect` parameter and use the port I run my server on, it works.

It seems as the master server uses and lists the address and more importantly port from which it received the first announcment packet from my server for the connection address and the address it sends pings to.

https://github.com/TES3MP/TES3MP/blob/49be5b6405d6ab427e06ed350cf76c715a1f3bdd/apps/master/MasterServer.cpp#L164

This address tho seems to use an ephemeral port and not the port I configured. I belive there might ba a lot of NAT going on here... How can I make my server tell the master server the correct port it acutally runs on?

**Comment by testman42** [comment]
Incorrect port in server browser was usually caused by UPnP being enabled on the router / modem.
Could you check whether your router has it enabled? If it has, then try disabling it.
Then stop your TES3MP server and then wait a minute or two.
Make sure that your server is **not listed** in the server browser.
Only then start the server again. It should have correct port listed.
Please do tell us if the issue persists.

**Comment by Eric-Prokop** [comment]
Thanks for answering!

I'm not running the server on my local machines, but in a kubernetes cluster (on a vserver with microk8s).
Here is the kubefile I'm using:
```yaml
apiVersion: v1
kind: ConfigMap
metadata: 
  name: morrowind-configmap
  namespace: morrowind
data:
  entrypoint.sh: |
    #!/bin/bash
    
    set -e
    
    if [ ! -d "/server/data/data" ]
    then
      echo -e "Data folder empty, populating with CoreScripts"
      cp -a /server/CoreScripts/. /server/data/
      echo -e "Replacing Russian with German version in /server/data/data/requiredDataFiles.json"
      # Morrowind.esm
      sed -i 's/0x34282D67/0x5F9766E6/g' /server/data/data/requiredDataFiles.json
      # Tribunal.esm
      sed -i 's/0x211329EF/0x7C19567D/g' /server/data/data/requiredDataFiles.json
      # Bloodmoon.esm
      sed -i 's/0x9EB62F26/0xF6FC8BE4/g' /server/data/data/requiredDataFiles.json
    fi
    
    # I removed env parsing, since I'm mounting a config directly
    
    ./tes3mp-server $@
  tes3mp-server-default.cfg: |
    [General]
    localAddress = 0.0.0.0
    port = 30062
    maximumPlayers = 64
    hostname = BG Server
    #0 - Verbose (spam), 1 - Info, 2 - Warnings, 3 - Errors, 4 - Only fatal errors
    logLevel = 1
    password = NelsonPandelaFromPandelaRush
    
    [Plugins]
    home = /server/data
    plugins = serverCore.lua
    
    [MasterServer]
    enabled = false
    address = master.tes3mp.com
    port = 25561
    rate = 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: morrowind-server
  namespace: morrowind
spec:
  selector:
    matchLabels:
      app: morrowind-server
  template:
    metadata:
      labels:
        app: morrowind-server
    spec:
      containers:
      - name: morrowind-server
        image:  docker.io/tes3mp/server:0.8.1
        volumeMounts:
          - name: morrowind-config-volume
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
          - name: morrowind-config-volume
            mountPath: /server/tes3mp-server-default.cfg
            subPath: tes3mp-server-default.cfg
          - name: morrowind-data-volume
            mountPath: /server/data
        ports:
          - name: game
            containerPort: 30062
      volumes:
      - name: morrowind-config-volume
        configMap:
          name: morrowind-configmap
      - name: morrowind-data-volume
        hostPath:
          path: /opt/morrowind # Path of the directory on the Host (node)
          type: DirectoryOrCreate # Directory, FileOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: morrowind-server-service
  namespace: morrowind
spec:
  type: NodePort
  selector:
    app: morrowind-server
  ports:
  - protocol: UDP
    port: 30062
    targetPort: 30062
    nodePort: 30062
```
Can you elaborate why UPnP is usually a problem? Maybe thats a good starting point for me to start investigating.
